# Generated by Django 5.0.6 on 2024-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(max_length=50)),
                ('task_status', models.BooleanField(default=False)),
                ('taks_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
